Query data from multiple tables using sql joins
NoelLincoln/vetclinic-db pull request #4
Opened 2023-11-10 19:31 UTC by NoelLincoln

Hello 👋,

In this milestone I was able to create these tables:
- 'vets'
- 'specializations' table to handle the relationship between species and vets.
- 'visits' to handle this between animals and vets.

I added the data as per the data.sql file

I finally queried data from the tables :

- Who was the last animal seen by William Tatcher?
![last animal seen by William Tatcher](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/2dba5855-5dde-42dc-ac78-c53fc49dbf3d)

- How many different animals did Stephanie Mendez see?
![How many different animals did Stephanie Mendez see](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/92284eb6-dbb0-4ac6-b0df-3cba7d511e86)

- List all vets and their specialties, including vets with no specialties.
![all vets and their specialties, including vets with no specialties](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/c942a92f-8425-4e5b-9ed3-9e632b4a0ea8)

- List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020
![all animals that visited Stephanie Mendez between April 1st and August 30th, 2020](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/2d99e4d1-457d-47d9-a4d9-b8f427004615)

- What animal has the most visits to vets?
![What animal has the most visits to vets](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/b95ea340-67ca-4ab9-8aaa-f8896f1831fd)

- Who was Maisy Smith's first visit?
![Maisy Smith's first visit](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/ab91fe94-f284-4b9d-895e-941eaf6f8f5f)

- Details for most recent visit: animal information, vet information, and date of visit.
![Details for most recent visit animal information vet information and date of visit](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/09c8afb9-23bf-4aa5-a439-141e82a39dce)

- How many visits were with a vet that did not specialize in that animal's species?
![How many visits were with a vet that did not specialize in that animals species](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/211d989a-f386-44a8-9958-bc5879bd5bea)

- What specialty should Maisy Smith consider getting? Look for the species she gets the most.
![What specialty should Maisy Smith consider getting the species she gets the most](https://github.com/NoelLincoln/vetclinic-db/assets/23360657/65c3e6e3-f7a6-41c6-ae59-dd2a2190f374)

Cheers!

2023-11-10 20:24 UTC, franclobo requested changes
Hi @NoelLincoln, 

# Required Changes ♻️

![so-close-jim-halpert](https://github.com/NoelLincoln/vetclinic-db/assets/58642949/ab8d82a7-0e6e-4862-a298-9e6422601bfa)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Correct schema ✔️ 
- Correct data ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 20:24 UTC, franclobo commented on queries.sql
> +    AND v.visit_date BETWEEN '2020-04-01' AND '2020-08-30';
- There are two visits to Stephanie Mendez from April 1st and August 30th, 2020. Those are 👇🏽 

> Agumon visited Stephanie Mendez on Jul 22th, 2020.
> Blossom visited Stephanie Mendez on May 24th, 2020.

Please 🙏🏽 fix this query to have the correct information.

2023-11-10 20:24 UTC, franclobo commented on queries.sql
> +LIMIT 1;
- [ ] Boarmon has the most visits to the vet these are 4, please 🙏🏽 fix this query to have the correct information.

> Boarmon visited Maisy Smith on Jan 24th, 2019.
> Boarmon visited Maisy Smith on May 15th, 2019.
> Boarmon visited Maisy Smith on Feb 27th, 2020.
> Boarmon visited Maisy Smith on Aug 3rd, 2020.

2023-11-10 20:24 UTC, franclobo commented on queries.sql
> +LIMIT 1;
- [ ] Maisy Smith has 9 visits, 6 Digimon, and 3 Pokemon. Please 🙏🏽 fix this query to have the correct information.

2023-11-10 20:24 UTC, franclobo commented on queries.sql
> +    OR s.species_id IS NULL;
- Maisy Smith doesn't have specialization so the number of visits should be more than 9 visits. Please 🙏🏽 fix this query to have the correct information.

2023-11-11 08:10 UTC, shella12 requested changes
Hi <STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Added queries, schema and data in appropriate files ✅ 
- Descriptive pull request with screenshots ✅ 

 ## Required Changes ♻️

- [ ] I have noticed that you have not made any changes to your PR. Please make sure that you address all the changes requested by the previous reviewer before submiting another request.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-11 09:18 UTC, shahadat3669 approved these changes
Hi @NoelLincoln, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ Worked on previous reviewer comments
✅ Updated screenshots. 👍 
✅ The code is top-notch! 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-11 09:27 UTC, merged